name: CD

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set Docker credentials for Jib
        run: |
          echo "jib.to.auth.username=${{ secrets.DOCKERHUB_USERNAME }}" >> gradle.properties
          echo "jib.to.auth.password=${{ secrets.DOCKERHUB_PASSWORD }}" >> gradle.properties

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push with Jib using multiple tags
        run: |
          ./gradlew jib -Djib.to.image=${{ secrets.DOCKER_REPO }}/fosslight -Djib.to.tags=latest,8.0
